In [2]:
import numpy as np

arr = np.array([  1,2,3])
print(arr.ndim)

1


In [4]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
arr = np.linspace(0,10,5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [ ]:
arr = np.full(2,2),np.inf
print(arr)

(array([2, 2]), inf)


In [10]:
arr = np.array([[10,20,30],[40,50,60]])
print(arr[: , 1]) 

[20 50]


In [11]:
arr = np.random.rand(2,3)
print(arr)

[[0.11200904 0.322018   0.08487844]
 [0.05357729 0.62044455 0.38169453]]


In [12]:
arr = np.array([1,2,3,4,5])
arr[1:4 ] = 0
print(arr)

[1 0 0 0 5]


In [25]:
Celcius = np.array([30,20,40,50,21])
Feren= Celcius.copy()
a= np.array([])

for i in np.nditer(Feren):
    Val=i*1.8+32
    a = np.append(a,Val)
    
print(a)

[ 86.   68.  104.  122.   69.8]


In [3]:
time = [400,300,200.5,430,500]
arr = np.array([time])
print(arr)
print(arr.shape)
print(arr.size)
print(arr.dtype)
timeInMin = arr / 60
print(timeInMin)


[[400.  300.  200.5 430.  500. ]]
(1, 5)
5
float64
[[6.66666667 5.         3.34166667 7.16666667 8.33333333]]
