In [2]:
import numpy as np 

In [ ]:
arr = np.array (1,24,5,6,7,2)
print(arr)

[ 1 24  5  6  7  2]


In [6]:
arr = np.array((2,3))
print(arr)

[2 3]


In [16]:
np.zeros((2, 3))     # সব 0 দিয়ে matrix
np.ones((3, 3))      # সব 1 দিয়ে matrix
np.eye(3)            # Identity Matrix
np.arange(0, 10, 2)  # 0 থেকে 10 পর্যন্ত, ২ করে বাড়ে
np.linspace(0, 1, 5) # 0 থেকে 1 এর মাঝে ৫টা value


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [20]:
P= np.arange(0,20,2)
print(P.dtype)
print(P)

int64
[ 0  2  4  6  8 10 12 14 16 18]


In [23]:
np.linspace(0,10,19)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ,
        5.55555556,  6.11111111,  6.66666667,  7.22222222,  7.77777778,
        8.33333333,  8.88888889,  9.44444444, 10.        ])

In [33]:
arr = np.array([1,2,3,4,5,66,6,6,3,2])
print(arr[6])
print(arr[4:9])
print(arr.dtype)
print(arr.shape)
arr.reshape(10,1)

6
[ 5 66  6  6  3]
int64
(10,)


array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [66],
       [ 6],
       [ 6],
       [ 3],
       [ 2]])

In [38]:

arr2 = np.array([[1, 2, 3], [4, 5, 6],[2,3,4],[5,4,3],[2,1,3]])
print(arr2[0][1])   # 2
print(arr2[1:3, :])   # [ 4 5 6]
print(arr2[3:4, :])
 

2
[[4 5 6]
 [2 3 4]]
[[5 4 3]]


In [41]:
 a= np.array([1,2,4])
 b = np.array([3,3,4])
 print(a+b)
 print(a/b)

[4 5 8]
[0.33333333 0.66666667 1.        ]


In [44]:
arr = np.array([[1,2],[2,2],[3,3],[3,3] ])
print(arr)
print()
print(arr.reshape(2,4))

flattened_arr = arr.flatten()
print(flattened_arr)

[[1 2]
 [2 2]
 [3 3]
 [3 3]]

[[1 2 2 2]
 [3 3 3 3]]
[1 2 2 2 3 3 3 3]


In [48]:
np.random.rand(2,3)  # ২ রো, ৩ কলাম এর random matrix
print(np.random.rand(2,3))
np.random.randint(0,5, (4,3))  # ০ থেকে ৫ এর মাঝে random integer matrix

[[0.42708973 0.87850133 0.81311929]
 [0.62269253 0.52026728 0.3348578 ]]


array([[1, 4, 3],
       [4, 4, 4],
       [1, 1, 2],
       [0, 1, 2]], dtype=int32)

In [ ]:
arr = np.array([1,2,3,45,5,6,3,2,3,4,5,6,7,8,9])
 # সব element এর যোগফল
print(np.sum(arr))
print(np.mean(arr))
print(arr.mean())
arr = np.array([1, 2, 3, 4, 5])

print(np.sum(arr))       # যোগফল
print(np.mean(arr))      # গড়
print(np.max(arr))       # সবচেয়ে বড়
print(np.min(arr))       # সবচেয়ে ছোট
print(np.std(arr))       # standard deviation


109
7.266666666666667
7.266666666666667


In [67]:
arr = np.random.randint(1,10,(3,3))
print(arr)

print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.reshape(2,4))


[[1 8 9]
 [3 4 8]
 [6 7 6]]
52
5.777777777777778
9


ValueError: cannot reshape array of size 9 into shape (2,4)

In [70]:
arr = np.arange(1,10).reshape(3,3)
print(arr)
arr[0:8]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:

arr = np.array([10, 20, 30, 40, 50])
arr[1:4]   # [20 30 40]
arr[:3]    # [10 20 30]
arr[3:]    # [40 50]
arr[::2]   # [10 30 50] (step=2)(prori 2 step e ekta kore nichi , like 0 te 1 ta then 2nd e 1 ta )



array([10, 20, 30, 40, 50])

In [86]:
arr = np.arange(1,10).reshape(3,3)
print(arr)
print(arr[:,[1]])
print()
print(arr[:,1:2])
print(arr[arr>5])
print(arr[1:,])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2]
 [5]
 [8]]

[[2]
 [5]
 [8]]
[6 7 8 9]
[[4 5 6]
 [7 8 9]]


In [91]:

arr = np.array([10, 20, 30, 40, 50])
new_arr = np.where(arr > 25, 1, 0)
print(new_arr)  # Output: [0 0 1 1 1]
print()
arr = np.array([10, 20, 30, 40, 50])
indexes = np.argwhere(arr > 25)
print(indexes)  # Output: [[2], [3], [4]]
print()

arr = np.array([10, 20, 30, 40])
sample = np.random.choice(arr, size=(2,4))
sample = np.random.choice(arr, size=2)
print(sample)  # Example: [30 10]


[0 0 1 1 1]

[[2]
 [3]
 [4]]

[10 30]
