# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.


In [20]:
import numpy as np

# Step 1: Create a 5x5 array with random integers between 1 and 20
random_array = np.random.randint(1, 21, size=(5, 5))
print("Original Array:\n", random_array)

# Step 2: Replace the third column (index 2) with 1
random_array[:, 2] = 1
print("\nModified Array:\n", random_array)

Original Array:
 [[16 19  5 18  2]
 [20  2 10  3  6]
 [20 16 14 10  1]
 [ 3  3 14 14 19]
 [20  3 15 16 17]]

Modified Array:
 [[16 19  1 18  2]
 [20  2  1  3  6]
 [20 16  1 10  1]
 [ 3  3  1 14 19]
 [20  3  1 16 17]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [27]:
import numpy as np 
arr= np.arange(1,37).reshape(6,6)
print(arr)

subArray = arr[2:5,1:4]
print(subArray)

array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Extract the elements on the border
border_elements = np.concatenate((array[0, :], array[-1, :], array[1:-1, 0], array[1:-1, -1]))
print("Border elements:")
print(border_elements)


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[14 15 16]
 [20 21 22]
 [26 27 28]]
Original array:
[[14 17 12  1  7]
 [ 8 11 14 14 19]
 [ 8 19 15 17 13]
 [16  6  2 15  8]
 [16  7 10 12  2]]
Border elements:
[14 17 12  1  7 16  7 10 12  2  8  8 16 19 13  8]


In [28]:
# Create two NumPy arrays of shape (3, 4) filled with random integers
array1 = np.random.randint(1, 11, size=(3, 4))
array2 = np.random.randint(1, 11, size=(3, 4))
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)

# Perform element-wise operations
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print("Element-wise addition:")
print(addition)
print("Element-wise subtraction:")
print(subtraction)
print("Element-wise multiplication:")
print(multiplication)
print("Element-wise division:")
print(division)

Array 1:
[[8 7 5 3]
 [3 6 6 8]
 [9 4 3 3]]
Array 2:
[[ 1  6 10 10]
 [ 7  4  8  7]
 [ 4  7 10  7]]
Element-wise addition:
[[ 9 13 15 13]
 [10 10 14 15]
 [13 11 13 10]]
Element-wise subtraction:
[[ 7  1 -5 -7]
 [-4  2 -2  1]
 [ 5 -3 -7 -4]]
Element-wise multiplication:
[[ 8 42 50 30]
 [21 24 48 56]
 [36 28 30 21]]
Element-wise division:
[[8.         1.16666667 0.5        0.3       ]
 [0.42857143 1.5        0.75       1.14285714]
 [2.25       0.57142857 0.3        0.42857143]]


In [29]:
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Compute the statistical values
mean = np.mean(array)
median = np.median(array)
std_dev = np.std(array)
variance = np.var(array)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)
print("Variance:", variance)

Original array:
[[ 1 13 17 11 12]
 [ 1  3  5  2 10]
 [ 9 11  6  4  8]
 [ 2 20  6  3 16]
 [10 14  9  5 11]]
Mean: 8.36
Median: 9.0
Standard Deviation: 5.144939261060328
Variance: 26.470399999999998


In [30]:
# Create a NumPy array of shape (3, 3) filled with random integers
array = np.random.randint(1, 11, size=(3, 3))
row_array = np.random.randint(1, 11, size=(3,))
print("Original array:")
print(array)
print("1D array:")
print(row_array)

# Add the 1D array to each row of the 2D array using broadcasting
result = array + row_array
print("Resulting array:")
print(result)

Original array:
[[1 8 9]
 [6 8 3]
 [4 8 5]]
1D array:
[5 3 7]
Resulting array:
[[ 6 11 16]
 [11 11 10]
 [ 9 11 12]]


In [31]:
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Flatten the array
flattened_array = array.flatten()
print("Flattened array:")
print(flattened_array)

# Reshape the array back to (5, 5)
reshaped_array = flattened_array.reshape((5, 5))
print("Reshaped array:")
print(reshaped_array)

Original array:
[[19 13 11 13 18]
 [10  2 15  1 18]
 [ 6 12 20  4  4]
 [11 16  1  9 14]
 [ 9  5 19  4  3]]
Flattened array:
[19 13 11 13 18 10  2 15  1 18  6 12 20  4  4 11 16  1  9 14  9  5 19  4
  3]
Reshaped array:
[[19 13 11 13 18]
 [10  2 15  1 18]
 [ 6 12 20  4  4]
 [11 16  1  9 14]
 [ 9  5 19  4  3]]
